#!/usr/bin/env php
<?php
// Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)

function genInputs() {
    while(($input = rtrim(fgets(STDIN))) !== false) {
        foreach (explode(' ', $input) as $v) {
            yield $v;
        }
    }
}
function getNext($gen) {
    $value = $gen->current();
    $gen->next();
    return $value;
}
$gen = genInputs();

$N = (int)getNext($gen);
$M = (int)getNext($gen);
$hints = [];
$hint_counts = array_fill(0, $N, 0);
for ($i = 0; $i < $M; $i++) {
    $X = (int)getNext($gen);
    $Y = (int)getNext($gen);
    $Z = (int)getNext($gen);

    $hints[$X][$Y] = true;
    $hints[$Y][$X] = true;
}
$clear = array_fill(0, $N, false);
arsort($hint_counts);
$magic = 0;
$chain = function($k) use($hints, &$clear, &$chain) {
    if ($clear[$k]) {
        return;
    }
    $clear[$k] = true;
    if (!isset($hints[$k])) {
        return;
    }
    foreach ($hints[$k] as $v => $tr) {
        $chain($v);
    }
};
for ($i = 1; $i <= $N; $i++) {
    if ($clear[$i]) {
        continue;
    }
    $magic++;
    if (!isset($hints[$i])) {
        continue;
    }
    $chain($i);
}
echo $magic.PHP_EOL;
