#!/usr/bin/env php
<?php
// Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
function solve(string $S)
{
    $z = 0;
    $o = 0;
    $toggle = true;
    for($i = 0; $i < strlen($S); $i++) {
        $v = (int)($S[$i]);
        if ($toggle) {
            if ($v) {
                $z++;
            } else {
                $o++;
            }
        } else {
            if ($v) {
                $o++;
            } else {
                $z++;
            }
        }
        $toggle = !$toggle;
    }
    echo min($o, $z).PHP_EOL;
}

fscanf(STDIN, '%s', $S);
solve($S);

