#!/usr/bin/env php
<?php
// Generated by 1.1.3 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
function solve(int $N, array $H)
{
    $max = array_shift($H);
    $count = 1;
    foreach ($H as $i) {
        if ($i >= $max) {
            $count++;
            $max = $i;
        }
    }
    echo $count.PHP_EOL;
}

fscanf(STDIN, '%d', $N);
$H = explode(' ', fgets(STDIN)); // array
solve($N, $H);

